### ISSUE TITLE
Making a PR for upstream

### ISSUE THREAD

**Issue by alexanderadam** [gardner/smtp-to-sendgrid-gateway#1]
Hi Gardner,

would you consider making a PR for getting those patches to the upstream fork?

**PS:** I'm not related to the upstream fork

**Comment by jordantrizz** [comment]
> Hi Gardner,
> 
> would you consider making a PR for getting those patches to the upstream fork?
> 
> **PS:** I'm not related to the upstream fork

Looks like he did something https://github.com/FGRibreau/smtp-to-sendgrid-gateway/pull/10

I'm looking to add in support for mailgun and other providers, just don't know how dead the project is.

**Comment by alexanderadam** [comment]
Ah my fault! :man_facepalming: Thank you for pointing me to that.

> I'm looking to add in support for mailgun and other providers, just don't know how dead the project is.

Sounds wonderful! I guess Gardner's repository is a better bet then.

**Comment by jordantrizz** [comment]
> Ah my fault! 🤦‍♂ Thank you for pointing me to that.
> 
> > I'm looking to add in support for mailgun and other providers, just don't know how dead the project is.
> 
> Sounds wonderful! I guess Gardner's repository is a better bet then.

It seems like it, I might fork and pr once I learn how to code in node!

**Comment by alexanderadam** [comment]
> I might fork and pr once I learn how to code in node!

In case you have fun coding on it: currently `smtp-to-sendgrid-gateway` does not support attachments but Gardner wrote me once:

> The code is based on @sendgrid/mail so you would just need to fork it and add an attachments array somewhere around [here](https://github.com/gardner/smtp-to-sendgrid-gateway/blob/master/server.js#L30).
>
> You can read about the attachments array in the docs here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/attachments.md
>
> You will also want to check out the [Mailparser docs](https://nodemailer.com/extras/mailparser/#attachment-object).

Initially I planned to do it but I didn't have time for it. :disappointed:

**Comment by jordantrizz** [comment]
Oooo thanks!

> Initially I planned to do it but I didn't have time for it. 😞

Same, so many great things to do but little time to complete them.
